language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run before to run tests
before_script: 
  flake8 --ignore=E501,E402 --exclude=venv
# command to run tests
script:
  nose2 --with-coverage
after_success:
  coveralls
# safelist
branches:
  only: master